### PR TITLE
Ability to clear all caches

### PR DESCRIPTION
**Pull request by tenorok**
it's very convenient to be able to clear all caches at one call.

### CODE REVIEW

**Comment by LouisTakePILLz** [comment]
You can rebase off the latest commits. The test suite should pass now.

**Comment by tenorok** [comment]
Done.

**Comment by tenorok** [comment]
@boblauer what do you think?

**Comment by boblauer** [comment]
Thank you for the reminder. I'll get this published later today.

**Comment by boblauer** [comment]
Thanks for the pull request.  Published on npm `@7.0.0`

**Pull request merged**
